### ISSUE TITLE
Error installing npm packages

### ISSUE THREAD

**Issue by dgorobets** [hzdg/cookiecutter-webpack#14] opened 2016-08-07 21:50 UTC
Hello, I'm running "run install" and get error:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.20 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.0 wants webpack@^2.1.0-beta
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dgorobets/anons/npm-debug.log

**Comment by goldhand** [comment] 2016-08-14 23:52
@dmitra90 are you still having trouble with this since the last update? Webpack and plugins have been getting a lot of updates lately. Wondering if thats the cause of this issue.

**Comment by dgorobets** [comment] 2016-08-15 06:43
Hi!

I tried again after updating cookiecutter-webpack and faced with another dependencies error:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.1-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.3.1-rc.1 wants react@^15.3.1-rc.1
npm ERR! peerinvalid Peer react-redux@5.0.0-alpha.1 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-router@3.0.0-alpha.3 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-addons-test-utils@15.3.0 wants react@^15.3.0
npm ERR! peerinvalid Peer redux-devtools-multiple-monitors@1.0.1 wants react@>=0.14.0
npm ERR! peerinvalid Peer redux-devtools-dispatch@2.2.0 wants react@>=0.14.0
npm ERR! peerinvalid Peer redux-slider-monitor@1.0.7 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer redux-devtools-dock-monitor@1.1.1 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer redux-devtools@3.3.1 wants react@^0.14.0 || ^15.0.0-rc.1
npm ERR! peerinvalid Peer redux-devtools-log-monitor@1.0.12-alpha wants react@^0.14.0 || ^15.0.0-0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dgorobets/web/npm-debug.log

**Comment by blessingoraz** [comment] 2016-09-23 12:01
Hello @dmitra90 , I ran into the same issue. You need to update your npm to the latest version by doing  `npm install -g npm`. I hope it helps.

**Comment by goldhand** [comment] 2016-09-24 19:05
thanks @andela-borazulume closing now

**Closed as completed by goldhand** 2016-09-24 19:05 UTC
Labels: bug

**Comment by pinguin999** [comment] 2021-03-09 17:19
Have the same error. But I'm on windows is that a problem?
